### ISSUE TITLE
我与动漫的羁绊

### ISSUE THREAD

**Issue by nc-animation** [gege-circle/home#162]
https://www.bilibili.com/read/cv339401
![88217247_p0](https://user-images.githubusercontent.com/69033087/111455283-90b75700-8750-11eb-905b-0c6cc91fb487.jpg)

**Comment by angran-samaa** [comment]
@nc-animation 戈大大你好，请问你能分享我的画作到微博上吗？我现在没有微博账号，所以拜托你了。
<img src="https://user-images.githubusercontent.com/69033087/114268664-c6401f00-9a34-11eb-8af7-e26737bd1be6.gif" width="180" />

**Comment by nc-animation** [comment]
@angran-samaa 可以的，有问题尽管找我吧
